### ISSUE TITLE
refreshing in settings tab cause error

### ISSUE THREAD

**Issue by YTG2G3** [YTG2G3/myextraduty#17]
![image](https://github.com/YTG2G3/myextraduty/assets/44752495/b7c70d44-3eec-4508-b94c-8d197ce5cf8a)

First visit to settings doesn't cause any errors, but as soon as I refresh it, hydration error occurs

**Comment by YTG2G3** [comment]
fixed.

**Comment by YTG2G3** [comment]
never mind, not fixed

**Comment by issac4892** [comment]
? i fixed

**Comment by issac4892** [comment]
fixed by changin g p to span
