### ISSUE TITLE
avatar not loading

### ISSUE THREAD

**Issue by YTG2G3** [YTG2G3/myextraduty#19]
![image](https://github.com/YTG2G3/myextraduty/assets/44752495/d71bf675-7f86-4bc1-9276-89c7e3d86c29)

**Comment by issac4892** [comment]
can't repoduce

**Comment by issac4892** [comment]
fixed by changing p to span

**Comment by YTG2G3** [comment]
![image](https://github.com/YTG2G3/myextraduty/assets/44752495/43aff627-aa51-413b-a3d8-44fd4e88929e)

fixed
